{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://httpbin.org/"
    }
  ],
  "info": {
    "title": "example results",
    "version": "1.0"
  },
  "paths": {
    "/example": {
      "get": {
        "description": "Showcase of responses with an `example` property present.",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": {
                  "id": 12345,
                  "email": "test@example.com",
                  "name": "Test user name"
                }
              }
            }
          },
          "206": {
            "description": "OK",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 12345,
                    "email": "test@example.com",
                    "name": "Test user name"
                  }
                ]
              }
            }
          }
        }
      },
      "delete": {
        "description": "Showcase of an operation with responses that contain no examples.",
        "responses": {
          "204": {
            "description": "No content"
          }
        }
      }
    },
    "/examples": {
      "description": "Showcase of responses with an `examples` property present.",
      "get": {
        "responses": {
          "default": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "$ref": "#/components/schemas/UserResponse/example"
                    }
                  }
                }
              },
              "text/csv, text/comma-separated-values": {
                "examples": {
                  "display_view=app": {
                    "value": "app1,app2,app3,app4,app5"
                  }
                }
              }
            }
          },
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "user": {
                    "value": {
                      "user": {
                        "email": "test@example.com",
                        "name": "Test user name"
                      }
                    }
                  }
                }
              }
            }
          },
          "202": {
            "description": "OK",
            "content": {
              "application/json": {
                "examples": {
                  "cat" : {
                    "summary": "An example of a cat",
                    "value": {
                      "name": "Fluffy",
                      "petType": "Cat",
                      "color": "White",
                      "gender": "male",
                      "breed": "Persian"
                    }
                  },
                  "dog": {
                    "summary": "An example of a dog with a cat's name",
                    "value": {
                      "name": "Puma",
                      "petType": "Dog",
                      "color": "Black",
                      "gender": "Female",
                      "breed": "Mixed"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-Response-Ref"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UserResponse": {
        "example": {
          "user": {
            "email": "test@example.com",
            "name": "Test user name"
          }
        }
      }
    },
    "responses": {
      "400-Response-Ref": {
        "description": "Validation failed",
        "content": {
          "application/xml": {
            "examples": {
              "response": {
                "value":
                  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><note><to>Tove</to><from>Jani</from><heading>Reminder</heading><body>Don't forget me this weekend!</body></note>"
              }
            }
          }
        }
      }
    }
  },
  "x-readme": {
    "explorer-enabled": true,
    "samples-enabled": true,
    "samples-languages": [
      "c",
      "clojure",
      "cplusplus",
      "csharp",
      "curl",
      "go",
      "java",
      "javascript",
      "kotlin",
      "node",
      "objectivec",
      "ocaml",
      "php",
      "powershell",
      "python",
      "r",
      "ruby",
      "swift"
    ]
  }
}
